### ISSUE TITLE
Add Search (React)

### ISSUE THREAD

**Issue by NicholasLYang** [NicholasLYang/school-seeker#10]
Add a search bar to the page. It doesn't have to do anything just yet, but it should be reasonably styled (i.e. not the default input styles) and available on every page. It should be its own component too (i.e. make a SearchBar component)

**Comment by oyin-k** [comment]
Hello @NicholasLYang Its my first time contributing and i want to start with this. Is there any more info you would like me to know to get started on this.

**Comment by NicholasLYang** [comment]
Hi @oyin-k! Great! I'll help you get started. I would create a new file in client/src/js/modules/core/components called SearchBar.tsx. This will be a React component, consisting of an input and some styles. For styles we're using [React JSS](https://github.com/cssinjs/react-jss). The way this works is, you define your styles in a JS object, then wrap the component in a higher order component called injectSheet. To get an idea of how that works, check out other components, like School.tsx.

Once you create the component, let me know and we can discuss where to put it. Feel free to ask me any questions whatsoever. If you're not familiar with React, TypeScript, or really any part of the stack, I'll be happy to teach you what I know. Good luck!

**Comment by oyin-k** [comment]
Thanks @NicholasLYang  I'm so on this. Will hit you up soonest.

**Comment by oyin-k** [comment]
Hello @NicholasLYang  I'm having some difficulty getting [rbenv ](https://github.com/rbenv/rbenv)to work on my windows machine.

**Comment by NicholasLYang** [comment]
Unfortunately, I don't use Windows, but I've found [this site](https://gorails.com/setup/windows/10) very useful for setting up Ruby on Rails. If that doesn't work, I can try to find somebody who does use Rails on Windows to help. However, I would consider also trying out the Ubuntu subsystem for Windows (or even installing a version of Linux on your computer). A lot of programs only run on Unix based systems, so it'd be very useful to have regardless.

**Comment by oyin-k** [comment]
Ok thanks

**Comment by oyin-k** [comment]
Hey @NicholasLYang. I finally got the dev server to run but i'm not seeing anything on the front end (http://localhost:3002).

**Comment by oyin-k** [comment]
When i ran `sh install.sh` i saw this:

```
npm WARN chance-me@0.0.1 No repository field.
npm WARN chance-me@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 30.795s
```
when i ran `sh run.sh` i saw:

```
chance-me@0.0.1 dev C:\Users\Oyinkan\Documents\Code\Projects\OSS\chanceMe\chance-me\client
> node app --dev & gulp dev

C:\Users\Oyinkan\Documents\Code\Projects\OSS\chanceMe\chance-me\client/dist/dev
chance-me [v0.0.1] (DEV MODE)
-> currently running at http://localhost:3002 in HTTP Insecure mode
(to enable HTTPS, run app with the flags "https", "ssl_cert" and "ssl_key")
```

**Comment by NicholasLYang** [comment]
Yeah, you're probably not running this on bash. Are you running these commands on the Windows terminal? If so, they won't work. For now, could you `cd` into the client directory and run `gulp`? Let me know if that works.

**Comment by oyin-k** [comment]
Hello @NicholasLYang. How are you doing. i ran `gulp` and the home page came up but it i was getting this `Error. Data failed to fetch`.

**Comment by NicholasLYang** [comment]
Hey, sorry about all this mess. I wrote these scripts assuming a Unix based system, which in retrospect was not very smart. Anyways, that's great! This just means that the script `run.sh` isn't working. So as a work around, you can open two tabs in your command line. Then, in one tab `cd` into client and run `npm run dev`. In the other tab, simply run `bin/rails server`. Ideally, this should run the Rails server in one tab and the gulp dev server in the other tab. Let me know if it works!

**Comment by oyin-k** [comment]
Still not working @NicholasLYang when I run `bin/rails server` in bash. It's giving me this:  `Your Ruby version is 2.5.1, but your Gemfile specified 2.5.0 (Bundler::RubyVersionMismatch)`. I have been trying to get a work around or a fix but I'm still having issues with it.

**Comment by NicholasLYang** [comment]
Okay, yeah. Did you install rbenv with ruby-build as per the GoRails
tutorial? If so, you can install Ruby 2.5.1 by running `rbenv install
2.5.1` and then setting it as your global version by doing `rbenv global
2.5.1`

On Sat, Aug 4, 2018 at 4:59 PM, Oyinkan Oyetunmibi <notifications@github.com

**Comment by NicholasLYang** [comment]
Oops, make that 2.5.0, sorry

**Comment by oyin-k** [comment]
Hey @NicholasLYang. I wasnt able to get this to go but is there anyway i can contribute to this without all that setup i want to learn from the project and the tech stack.

**Comment by NicholasLYang** [comment]
Hey, unfortunately, you can't really contribute without being able to run the code. Did you ever install rbenv? The point of rbenv is that you can keep multiple versions of Ruby (like 2.5.1 and 2.5.0) on the same computer and switch between them easily. There's also an add on to rbenv called ruby-build that allows you to install these different versions easily. If you have these two things installed, you should be able to get Ruby 2.5.0 very easily and run the code. 

However, if you can't get this to run, I'll happily give you advice or feedback on any projects you're interested in. Let me know if you're working on anything in particular and I'll get back to you with feedback.

**Comment by oyin-k** [comment]
Heys thanks is there anyway we can chat privately.

**Comment by NicholasLYang** [comment]
Oops, sorry! Think I forgot to respond to this. Yeah, feel free to send me an email at ny585 at nyu.edu
